services:
  api-server:
    build: .
    container_name: api-server
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    depends_on:
      - redis
    env_file:
      - .env
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
  build-server:
    build:
      context: /Users/srb/Work/makethumb/build-server/
      dockerfile: Dockerfile
    image: build-server:latest
