version: "3.8"

services:
  api-server:
    build: .
    container_name: api-server
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
